[package]
name = "metaplex-anchor-sdk"
version = "0.1.0"
edition = "2021"
description = "Anchor wrapper for Metaplex program library"

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
mpl-token-metadata = { version="1.8.5", features = [ "no-entrypoint" ] }