[features]
seeds = false
skip-lint = false

[programs.localnet]
de_bridge = "HhX1RVWgGTLrRSiEiXnu4kToHZhFLpqi5qkErkfFnqEQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dependencies/mpl_token_metadata.so"

[[test.genesis]]
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"
program = "./dependencies/wormhole.so"
