[features]
seeds = false
skip-lint = false

[programs.localnet]
dust_bridging = "DxPDCoSdg5DWqE89uKh6qpsergPX8nd7DLH5EmyWY5uq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dependencies/mpl_token_metadata.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "./dependencies/wormhole.so"
